apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: seerr
  labels:
    dns.homelab/external: "true"
spec:
  endpoints:
  - dnsName: "seerr.${DOMAIN_5}"
    recordTTL: 60
    recordType: CNAME
    targets:
    - "external.${DOMAIN_5}"
