---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: seerr-internal
  labels:
    dns.homelab/external: "false"
spec:
  endpoints:
  - dnsName: "seerr.${DOMAIN_5}"
    recordTTL: 60
    recordType: CNAME
    targets:
    - "internal.${DOMAIN_5}"
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: seerr-external
  labels:
    dns.homelab/external: "true"
spec:
  endpoints:
  - dnsName: "seerr.${DOMAIN_5}"
    recordTTL: 60
    recordType: CNAME
    targets:
    - "external.${DOMAIN_5}"
