---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: lobby-auth-internal
  labels:
    dns.homelab/external: "false"
spec:
  endpoints:
  - dnsName: "ffxi.${DOMAIN_3}"
    recordTTL: 60
    recordType: A
    targets:
    - "${LOAD_BALANCER_IP}"
