apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant-goffxi-db-access
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: "goffxi"
  table: "*"
  username: goffxi
  grantOption: true
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
