---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: paperless
  labels:
    dns.homelab/external: "false"
spec:
  endpoints:
  - dnsName: "paperless.${DOMAIN_5}"
    recordTTL: 60
    recordType: CNAME
    targets:
    - "internal.${DOMAIN_5}"
